version: 2
updates:
- package-ecosystem: pip
  directory: "/"
  schedule:
    interval: daily
    time: "11:00"
  open-pull-requests-limit: 10
  reviewers:
  - calebcartwright
  assignees:
  - calebcartwright
  labels:
  - dependencies
  ignore:
  - dependency-name: black
    versions:
    - 21.4b1
